# Generated by Django 3.2.9 on 2021-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('slogan', models.TextField(default='Far far away, behind the word mountains, far from the countries Vokalia and Consonantia')),
                ('daily_visitor', models.IntegerField(default=10)),
                ('adress', models.TextField(help_text="enter company's current adress")),
                ('phone', models.CharField(default='+2 392 3929 210', max_length=155)),
                ('email', models.CharField(default='\tinfo@yourdomain.com', max_length=123)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
