# Generated by Django 3.2.8 on 2021-11-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fennler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenn', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muellimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=127, null=True)),
                ('soyad', models.CharField(blank=True, max_length=127, null=True)),
                ('tarix', models.DateTimeField(auto_now_add=True)),
                ('fenn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fennlers', to='mekteb.fennler')),
            ],
        ),
    ]
